name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Используйте ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Укажите вашу версию Node.js

      - name: Install dependencies
        run: npm ci

      - name: Build Quasar app
        run: npm run build

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REPOSITORY_NAME: Wunderkammer-Amsterdam/wunderkammer-amsterdam.github.io
      #     BRANCH: master # The branch the action should deploy to.
      #     FOLDER: dist # The folder the action should deploy.
# Укажите папку с вашим билдом
